resources:
    - name: repo
      type: git
      icon: github
      source:
          uri: https://github.com/fortinet/fortigate-autoscale-gcp.git
          branch: main
    - name: terraform-image
      type: registry-image
      icon: terraform
      source:
          repository: hashicorp/terraform
          tag: 1.1.8
    - name: node
      type: registry-image
      source:
          repository: node
          tag: 16.3.0-stretch

jobs:
    - name: terraform-deployment-pipeline
      plan:
          - get: node
          - get: terraform-image
          - get: repo
            trigger: true

          - task: node-install
            image: node
            config:
                inputs:
                    - name: repo
                outputs:
                    - name: dependencies
                      path: repo/node_modules
                platform: linux
                run:
                    path: npm
                    args: ['install']
                    dir: repo

          - task: dist
            image: node
            config:
                inputs:
                    - name: repo
                    - name: dependencies
                      path: repo/node_modules
                platform: linux
                run:
                    path: sh
                    args:
                        - -exc
                        - |
                            apt-get update
                            apt-get install -y zip
                            npm run setup
                    dir: repo

          - task: terraform-init
            image: terraform-image
            config:
                inputs:
                    - name: repo
                outputs:
                    - name: repo
                platform: linux
                run:
                    path: terraform
                    dir: repo
                    args:
                        - init

          - task: terraform-plan
            image: terraform-image
            config:
                inputs:
                    - name: repo
                outputs:
                    - name: repo
                platform: linux
                run:
                    path: terraform
                    dir: repo
                    args:
                        - plan
                        - -var
                        - project="dev-project-001-166400"
                        - -var
                        - service_account="966517025500-compute@developer.gserviceaccount.com"
                        - -var
                        - auth_key=((skunkworks.gcp-pipeline.account))
                        # - auth_key=((devops-publish.gcp-dev-project-001.account))
